package com.daggerbasicspractice.di

import android.content.Context
import com.daggerbasicspractice.AppClass
import dagger.BindsInstance
import dagger.Component
import dagger.android.AndroidInjectionModule
import dagger.android.AndroidInjector


@ApplicationScope
@Component(
    modules =
//this module is generated by dagger to inject in dispathing android injection field in appclass
    [AndroidInjectionModule::class,
        AppModule::class]
)
interface AppComponent :
    AndroidInjector<AppClass> {

    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): AppComponent
    }
}